### ISSUE TITLE
Features Planning 10/9

### ISSUE THREAD

**Issue by M8tth3** [M8tth3/ramjiJarmi#2]

**Comment by M8tth3** [comment]
- Add a face that moves
- Let user move through directories
- Cutscene
- Boss switching images

**Comment by rayanesouuuu1234** [comment]
**CHARACTER CREATION**

Using the post method, we are going to create a player in the data base for our backend

HTML Implementation:

Page Title: "Dark Souls: Character Creation"
Name Input: Text field to enter the character's name.
Class Dropdown: Options to select from: Knight, Thief, Sorcerer, Pyromancer, Cleric, Wanderer.
Age Input: Number field with a default value of 20.
Sex Selection: Radio buttons for Male, Female, or Other.
Action Buttons: "CONFIRM" and "CANCEL" buttons at the bottom.

CSS Implementation:
Page Background: Uses a Dark Souls themed background image.
General Font: Times New Roman with a specific light beige color.
Container: Centralized flex display with a slightly transparent dark background, a shadow effect, and an aesthetic border.
Labels: Displayed as block elements with a bottom margin.
